提示されたファイル群を確認・精査しました。
結論として、**「重複ファイルの削除」**と**「英日コード間の論理不整合の修正」**が必要です。

特に、英語版コード（EN）が日本語版コード（JP）よりも「先に進んでしまっている（あるいは解釈が異なる）」箇所があり、**Ver.1.0としての同一性が損なわれています。**

以下に詳細な処置内容を報告します。

---

### 1. 整理：必要なファイル構成

現在の提示物には重複や、Markdownの中にコードが含まれているものがあります。以下のように4つのファイルに整理するのが正解です。

| 状態 | ファイル名 | 判定 | 理由 |
| :--- | :--- | :--- | :--- |
| **残す** | `nra_ide_foundation_fixed_jp.py` | **Master** | 原本。Ver.1.0 安定版の基準。 |
| **修正して残す** | `nra_ide_foundation_fixed_en.py` | **Fix Req** | JP版と動作ロジックに乖離あり（後述）。 |
| **残す** | `律環公理_コード付き解説_二重ゆらぎ安定版.md` | **Master** | 解説の原本。 |
| **残す** | `Nomological_Ring_Axioms_Code_Annotated_Explanation_Dual_Fluctuation_Stable.md` | **Safe** | 翻訳は正確。 |
| **削除** | `nra_ide_foundation_fixed_en.md` | **Delete** | Pythonコードがmdファイルとして開始されているため不要。中身は`.py`と同じ。 |
| **削除** | 末尾の `nra_ide_foundation_fixed_jp.py` | **Delete** | 冒頭のファイルと同一の重複投稿。 |

---

### 2. 厳密な整合性チェック（バグ・不一致の指摘）

日本語版（JP）を「正」とした場合、英語版（EN）に以下の**致命的なロジック不一致**があります。これを修正しないと、言語によってシミュレーション結果（エネルギー収支）が変わってしまいます。

#### ① `BoundLaw.correct()` におけるエネルギー処理の違い
JP版では「既知の制約」としてエネルギー保存の不完全さを許容していますが、EN版では独自に `E_stored` を更新しようとしています。また、JP版は `E_dissipated` に計上していますが、EN版は `E_stored` に計上しています。

*   **JP (正):**
    ```python
    # 散逸(dissipated)として計上し、E_storedは複雑な差分計算を行う
    token.ledger.E_dissipated += excess
    token.ledger.E_stored     += max(0.0, target) - (token.state.value - excess)
    token.ledger.E_stored      = max(0.0, token.ledger.E_stored)
    ```
*   **EN (誤 - 現状):**
    ```python
    # E_storedに単純加算している（JPと挙動が異なる）
    token.ledger.E_stored += excess
    # token.ledger.E_dissipated への加算が欠落している
    ```

#### ② `RateLimitLaw.correct()` の処理過剰
JP版の `RateLimitLaw` はエネルギー収支（Ledger）に触れませんが、EN版では `E_stored` を加算しています。

*   **JP (正):** Ledgerへの操作なし。
*   **EN (誤):** `token.ledger.E_stored += excess` が記述されている。

#### ③ 変数名の微細な不一致
*   JP: `DynamicState` 内のコメント `[EXT: pressure] +0.0（未使用）`
*   EN: `[EXT: pressure] +0.0 (unused)`
    *   これは翻訳として適切ですが、コード内の動作に関わる部分は一致させる必要があります。

---

### 3. 修正版コードの提示

上記に基づき、**日本語版（Master）と論理的に完全に一致させた英語版コード**を生成しました。こちらに差し替えてください。

#### [FIXED] nra_ide_foundation_fixed_en.py
(修正点：`BoundLaw`と`RateLimitLaw`のロジックをJP版に完全準拠させました)

```python
# FILE: nra_ide_foundation_fixed.py
# Title: NRA-IDE Foundation - DynamicState Core with Extension Reservations [fixed]
# "Thickness + Fluctuation x2 ver.1.0 Stable Edition"
# Author: M-Tokuni / Copyright
# Date: 2026-02-21 04:52 JST

# [FIX LOG]
#  - BoundLaw.correct(): Corrected E_stored update from overwriting normalized values to differential accumulation.
#  - ObservationLog.record(): Expanded violation check to all targets (changed from [-1] only to any()).

# [KNOWN CONSTRAINTS / EXT RESERVATIONS]
#  - E_bal (Energy balance residual) remains positive because E_stored is tracked only during the correction phase.
#     Full conservation closure requires integrating E_stored across all phases.
#     -> Planned for the next version as [EXT: full_energy_closure].

# DESIGN PHILOSOPHY:
#   "DynamicState" is fixed as a "Container".
#   Even if the medium or target changes, the same container is used.
#   Each "Law" is swapped out as a transition function (defining how it moves).

# REGARDING EXTENSION RESERVATIONS:
#   Unimplemented dynamic terms are explicitly left as `* 1` or `+ 0.0`.
#   Comments are tagged with "[EXT: Extension Name]" — connection points for future implementation.
#   Do not delete, do not omit, do not average.

from __future__ import annotations

import math
import copy
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from typing import Any, Callable, Dict, List, Optional, Tuple

# ─────────────────────────────────────────────
# Utilities
# ─────────────────────────────────────────────

def jst_now() -> str:
    return (datetime.now(timezone.utc) + timedelta(hours=9)).strftime("%Y-%m-%d %H:%M:%S")


# ─────────────────────────────────────────────
# DynamicState (Normalized State Quantity / Container)
# ─────────────────────────────────────────────

@dataclass
class DynamicState:
    """
    Medium-independent normalized state quantity. value ∈ [0.0, 1.0].

    All dynamic calculations pass through this container.
    Differences in media are expressed by Laws (transition functions), keeping the container shape unchanged.

    Field Descriptions:
      value   : Current state value (0=Complete Stability, 1=Critical Limit).
      rate    : Rate of change dv/dt (Velocity).
      buffer  : Energy waiting for dissipation (Escape for errors. Do not erase).
      tension : Restoring force generated by distance from constraints (Tension).
      history : History of instantaneous values (Record of protrusions/spikes. Do not average).
    """
    value  : float = 0.0
    rate   : float = 0.0
    buffer : float = 0.0
    tension: float = 0.0
    history: List[float] = field(default_factory=list)

    # ── [EXT: pressure] ──────────────────────────────
    # Pressure term (Human body / Fluid systems)
    # Current: + 0.0 because it is unused.
    # Implementation: Add `pressure: float = 0.0`, and in TensionLaw.compute():
    #   tension += pressure_coefficient * self.pressure
    pressure: float = 0.0   # [EXT: pressure] +0.0 (Unused)

    # ── [EXT: viscosity] ─────────────────────────────
    # Viscosity coefficient (Suppresses rate of change. Makes sudden spikes physically impossible).
    # Current: * 1 (Multiplication, so effectively disabled).
    # Implementation: rate_limited = rate * viscosity_factor (0 < v_factor <= 1)
    viscosity_factor: float = 1.0   # [EXT: viscosity] *1 (Disabled)

    # ── [EXT: plasticity] ────────────────────────────
    # Plasticity deformation coefficient (The baseline shifts after exceedance. History dependent).
    # Current: * 1 (No baseline change).
    # Implementation: threshold_shift += plasticity * max(0, value - threshold)
    plasticity_factor: float = 1.0  # [EXT: plasticity] *1 (Disabled)

    def record(self, v: float) -> None:
        """Record instantaneous value as is (do not average)."""
        self.history.append(v)

    def peak(self) -> float:
        """Protrusion value (Maximum instantaneous value)."""
        return max(self.history) if self.history else 0.0

    def normalize(self, raw: float, raw_max: float) -> float:
        """Normalize dimensional physical quantity to [0, 1]."""
        return min(1.0, max(0.0, raw / raw_max)) if raw_max > 0 else 0.0

    def denormalize(self, norm: float, raw_max: float) -> float:
        """Inverse transform [0, 1] to dimensional physical quantity."""
        return norm * raw_max


# ─────────────────────────────────────────────
# EnergyLedger (Energy Balance Sheet)
# ─────────────────────────────────────────────

@dataclass
class EnergyLedger:
    """
    Recorder for the Law of Conservation of Energy.
    Validates E_in = E_stored + E_dissipated (Conservation Law) every cycle.

    Errors are escaped to the buffer (not erased).
    """
    E_in       : float = 0.0   # Input Energy (Disturbance / Action Cost)
    E_stored   : float = 0.0   # Energy stored in the system
    E_dissipated: float = 0.0  # Dissipated Energy (Released via buffer)

    # ── [EXT: thermal_dissipation] ───────────────────
    # Thermal dissipation (Loss during high-speed fluctuations. Current: +0.0)
    E_thermal  : float = 0.0   # [EXT: thermal_dissipation] +0.0

    def balance(self) -> float:
        """Error in conservation law = E_in - (E_stored + E_dissipated)"""
        return self.E_in - (self.E_stored + self.E_dissipated + self.E_thermal)

    def is_conserved(self, tol: float = 1e-6) -> bool:
        return abs(self.balance()) < tol


# ─────────────────────────────────────────────
# Token (Information Unit)
# ─────────────────────────────────────────────

@dataclass
class Token:
    """
    Data packet circulating in the Ring.
    state  : DynamicState (The Container)
    meta   : System management information
    ledger : Energy balance
    history: Observation log (Post-event recording only)
    """
    state  : DynamicState = field(default_factory=DynamicState)
    meta   : Dict[str, Any] = field(default_factory=dict)
    ledger : EnergyLedger = field(default_factory=EnergyLedger)
    history: List[Tuple[str, DynamicState]] = field(default_factory=list, repr=False)

    def __post_init__(self):
        self.meta.setdefault("cycle", 0)
        self.meta.setdefault("created_at", jst_now())
        self.meta.setdefault("violated_laws", [])
        self.meta.setdefault("infeasible", False)

    def snapshot(self, node_name: str) -> None:
        self.history.append((node_name, copy.deepcopy(self.state)))

    def increment_cycle(self) -> None:
        self.meta["cycle"] += 1

    def log_violation(self, law_name: str) -> None:
        self.meta["violated_laws"].append({
            "law": law_name,
            "cycle": self.meta["cycle"],
            "value": self.state.value,
            "tension": self.state.tension,
        })

    def __repr__(self) -> str:
        s = self.state
        return (f"Token(cycle={self.meta['cycle']}, "
                f"value={s.value:.3f}, rate={s.rate:.3f}, "
                f"buffer={s.buffer:.3f}, tension={s.tension:.3f})")


# ─────────────────────────────────────────────
# Law (Constraint / Dynamics Rule)
# ─────────────────────────────────────────────

class Law(ABC):
    """
    Abstract base class for dynamics rules acting on DynamicState.

    check()  : Whether constraints are satisfied.
    tension(): Restoring force (tension) proportional to distance from constraints.
    correct(): Correct the state using tension. Errors go to buffer.
    """

    @property
    def name(self) -> str:
        return self.__class__.__name__

    @abstractmethod
    def check(self, token: Token) -> bool: ...

    @abstractmethod
    def tension(self, token: Token) -> float:
        """
        Calculation of restoring force.
        Distance (excess amount) generates force — The principle that
        "deduction" does not derive force *from* distance, but implies
        "treating distance itself *as* force".
        Transformation via a proportional coefficient k is permissible.
        """
        ...

    @abstractmethod
    def correct(self, token: Token) -> Optional[Token]:
        """
        Correct using tension. Excess energy is escaped to buffer (not erased).
        Impossible correction → Returns None (Infeasibility).
        """
        ...


class BoundLaw(Law):
    """
    General Upper Bound Constraint.
    Guarantees that DynamicState.value does not exceed threshold.

    Tension: T = k * max(0, value - threshold)
    Correction: Pull value back to threshold - margin, move excess to buffer.
    """

    def __init__(
        self,
        threshold: float = 0.8,    # Upper limit (Normalized)
        k        : float = 1.0,    # Tension coefficient
        margin   : float = 0.05,   # Clip margin (Safe zone for next cycle)
    ):
        self.threshold = threshold
        self.k         = k
        self.margin    = margin

        # ── [EXT: viscosity_coupling] ─────────────────
        # Coupling viscosity to tension calculation (Add resistance as rate increases).
        # Current: +0.0
        # Implementation: T += viscosity * abs(token.state.rate)
        self._viscosity_coupling: float = 0.0  # [EXT: viscosity_coupling] +0.0

        # ── [EXT: brittle_threshold] ──────────────────
        # Brittle fracture point (Tension releases suddenly if this value is exceeded).
        # Current: * 1 (Remains standard linear tension).
        # Implementation: if value > brittle_threshold: T *= brittle_amplifier
        self._brittle_factor: float = 1.0      # [EXT: brittle_threshold] *1

    def check(self, token: Token) -> bool:
        return token.state.value <= self.threshold

    def tension(self, token: Token) -> float:
        excess = max(0.0, token.state.value - self.threshold)
        T = self.k * excess
        T += self._viscosity_coupling          # [EXT: viscosity_coupling]
        T *= self._brittle_factor              # [EXT: brittle_threshold]
        return T

    def correct(self, token: Token) -> Optional[Token]:
        T = self.tension(token)
        if T <= 0:
            return token

        excess = token.state.value - self.threshold
        target = self.threshold - self.margin

        # Escape excess energy to buffer (do not erase)
        token.state.buffer += excess
        token.state.value   = max(0.0, target)
        token.state.tension = T

        # Record in Energy Ledger (Aligned with JP version logic)
        # FIX: E_stored is cumulative difference (Corrected from overwriting normalized value -> causing errors)
        token.ledger.E_dissipated += excess
        token.ledger.E_stored     += max(0.0, target) - (token.state.value - excess)
        token.ledger.E_stored      = max(0.0, token.ledger.E_stored)  # Lower bound protection

        return token


class RateLimitLaw(Law):
    """
    Rate of Change Constraint (Foundation of Viscous Medium Model).
    Guarantees that rate does not exceed max_rate.

    Makes sudden spikes physically impossible — For Human Body / Soil Moisture systems.
    Disable (max_rate=inf) for Minerals / Pest systems.
    """

    def __init__(self, max_rate: float = 0.2):
        self.max_rate = max_rate

        # ── [EXT: rate_asymmetry] ─────────────────────
        # Set max_rate asymmetrically for increasing and decreasing directions.
        # Current: * 1 (Symmetric).
        # Implementation: Set max_rate_up / max_rate_down independently.
        self._rate_asymmetry: float = 1.0  # [EXT: rate_asymmetry] *1

    def check(self, token: Token) -> bool:
        return abs(token.state.rate) <= self.max_rate * self._rate_asymmetry

    def tension(self, token: Token) -> float:
        excess_rate = abs(token.state.rate) - self.max_rate
        return max(0.0, excess_rate)

    def correct(self, token: Token) -> Optional[Token]:
        if self.check(token):
            return token
        sign = 1.0 if token.state.rate >= 0 else -1.0
        # Accumulate exceeded rate into buffer
        token.state.buffer += abs(token.state.rate) - self.max_rate
        token.state.rate    = sign * self.max_rate
        return token


# ─────────────────────────────────────────────
# Node (Processing Unit)
# ─────────────────────────────────────────────

class Node(ABC):
    def __init__(self, name: str):
        self.name = name
        self._logger = logging.getLogger(f"NRA.{name}")

    @abstractmethod
    def process(self, token: Token) -> Token: ...

    def _record(self, token: Token) -> Token:
        token.snapshot(self.name)
        return token


class SafetyNode(Node):
    """Inference Diode cum Safety Verification Node. Applies all Laws."""

    def __init__(self, name: str, laws: List[Law]):
        super().__init__(name)
        self.laws = laws

    def process(self, token: Token) -> Token:
        for law in self.laws:
            T = law.tension(token)
            if T > 0:
                token.state.tension = T
            if not law.check(token):
                self._logger.warning(f"Violation: {law.name} | T={T:.4f} | v={token.state.value:.3f}")
                token.log_violation(law.name)
                result = law.correct(token)
                if result is None:
                    token.meta["infeasible"] = True
                    self._logger.error(f"Infeasibility: {law.name}")
                    return self._record(token)
                token = result
        return self._record(token)


class DynamicsNode(Node):
    """
    State Transition Node.
    Can inject `transition_fn`: (DynamicState, cycle) -> DynamicState externally.
    Swapped out for each medium.
    """

    def __init__(
        self,
        name: str,
        transition_fn: Optional[Callable] = None,
        raw_max: float = 100.0,
    ):
        super().__init__(name)
        self.transition_fn = transition_fn or self._default_transition
        self.raw_max = raw_max

    @staticmethod
    def _default_transition(state: DynamicState, cycle: int) -> DynamicState:
        """
        Default Transition: Linear Addition (*1 Medium coefficient, +0 Viscosity term).

        Changes value by +0.1 as an operation equivalent to `compute`.
        In real environments, swap `transition_fn` to use.
        """
        cost = 0.1   # Base cost

        # ── [EXT: viscosity] ─────────────────────────
        # Viscosity term: Suppress change in rate.
        # Current: * 1 (No suppression).
        # Implementation: cost *= state.viscosity_factor
        cost *= state.viscosity_factor   # [EXT: viscosity] *1

        # ── [EXT: pressure] ──────────────────────────
        # Pressure term: Additional cost.
        # Current: + 0.0
        # Implementation: cost += state.pressure * pressure_coefficient
        cost += state.pressure * 0.0     # [EXT: pressure] +0.0

        new_rate  = cost
        new_value = min(1.0, state.value + cost)
        state.rate  = new_rate
        state.value = new_value
        state.record(new_value)          # Record instantaneous value (do not average)
        return state

    def process(self, token: Token) -> Token:
        if token.meta.get("infeasible"):
            return self._record(token)
        token.state = self.transition_fn(token.state, token.meta["cycle"])
        # Energy Ledger: Record input amount
        token.ledger.E_in += token.state.rate
        return self._record(token)


class DisturbanceNode(Node):
    """
    Disturbance Injection Node.
    Specified by normalized value (magnitude ∈ [0, 1]).
    """

    def __init__(
        self,
        name: str,
        trigger_cycles: List[int],
        magnitude: float = 0.5,
    ):
        super().__init__(name)
        self.trigger_cycles = trigger_cycles
        self.magnitude = magnitude

    def process(self, token: Token) -> Token:
        if token.meta["cycle"] in self.trigger_cycles:
            self._logger.warning(
                f"Disturbance Injection [cycle={token.meta['cycle']}]: +{self.magnitude}"
            )
            prev = token.state.value
            token.state.value = min(1.0, token.state.value + self.magnitude)
            token.state.rate   = token.state.value - prev
            token.ledger.E_in += self.magnitude   # Account in Energy Ledger
            token.state.record(token.state.value)
        return self._record(token)


# ─────────────────────────────────────────────
# NomologicalRing (Law-Governed Ring Engine)
# ─────────────────────────────────────────────

class NomologicalRing:
    def __init__(self, nodes: List[Node]):
        self.nodes = nodes
        self._logger = logging.getLogger("NRA.Ring")

    def run_cycle(self, token: Token) -> Token:
        self._logger.debug(f"=== Cycle {token.meta['cycle']} ===")
        for node in self.nodes:
            token = node.process(token)
            if token.meta.get("infeasible"):
                self._logger.warning(f"Infeasibility @ {node.name}")
                break
        token.increment_cycle()
        return token

    def run(self, token: Token, max_cycles: int = 20) -> Token:
        for _ in range(max_cycles):
            token = self.run_cycle(token)
        return token


# ─────────────────────────────────────────────
# ObservationLog (Observation Layer)
# ─────────────────────────────────────────────

class ObservationLog:
    """Pure observation/visualization layer not involved in processing."""

    def __init__(self):
        self.records: List[Dict[str, Any]] = []

    def record(self, token: Token) -> None:
        s = token.state
        self.records.append({
            "cycle"    : token.meta["cycle"],
            "value"    : s.value,
            "rate"     : s.rate,
            "buffer"   : s.buffer,
            "tension"  : s.tension,
            "peak"     : s.peak(),
            "E_in"     : token.ledger.E_in,
            "E_stored" : token.ledger.E_stored,
            "E_dissip" : token.ledger.E_dissipated,
            "conserved": token.ledger.is_conserved(),
            # FIX: Detect ALL violations within the same cycle (Corrected accessing only [-1])
            "violated" : any(
                v["cycle"] == token.meta["cycle"] - 1
                for v in token.meta["violated_laws"]
            ),
        })

    def print_table(self) -> None:
        print(f"\n{'cycle':>5} | {'value':>6} | {'rate':>6} | "
              f"{'buffer':>7} | {'tension':>7} | {'peak':>6} | "
              f"{'E_bal':>6} | status")
        print("-" * 72)
        for r in self.records:
            bal = r["E_in"] - r["E_stored"] - r["E_dissip"]
            viol = "⚠️ " if r["violated"] else "✅"
            print(
                f"{r['cycle']:5d} | {r['value']:6.3f} | {r['rate']:+6.3f} | "
                f"{r['buffer']:7.3f} | {r['tension']:7.4f} | {r['peak']:6.3f} | "
                f"{bal:+6.4f} | {viol}"
            )

    def plot(self, save_path: str, threshold: float = 0.8) -> None:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        cycles  = [r["cycle"] for r in self.records]
        values  = [r["value"]  for r in self.records]
        buffers = [r["buffer"] for r in self.records]
        tension = [r["tension"] for r in self.records]

        fig, axes = plt.subplots(3, 1, figsize=(13, 10), sharex=True)

        # ── Top: state.value vs threshold ──
        axes[0].plot(cycles, values, marker="o", color="steelblue",
                     linewidth=2, label="state.value")
        axes[0].axhline(y=threshold, color="crimson", linestyle="--",
                        linewidth=1.5, label=f"threshold={threshold}")
        axes[0].fill_between(cycles, 0, threshold, color="limegreen",
                             alpha=0.07, label="Safe zone")
        for r in self.records:
            if r["violated"]:
                axes[0].axvspan(r["cycle"]-0.4, r["cycle"]+0.4,
                                color="orange", alpha=0.2)
        axes[0].set_ylabel("Normalized Value")
        axes[0].set_title("NRA-IDE Foundation: DynamicState Dynamics")
        axes[0].legend(fontsize=8)
        axes[0].grid(True, alpha=0.3)

        # ── Middle: buffer (Escape for errors) and tension ──
        axes[1].fill_between(cycles, 0, buffers, color="dodgerblue",
                             alpha=0.4, label="buffer (dissipated energy)")
        axes[1].plot(cycles, tension, color="crimson", linewidth=1.5,
                     label="tension (restoring force)")
        axes[1].set_ylabel("Buffer / Tension")
        axes[1].legend(fontsize=8)
        axes[1].grid(True, alpha=0.3)

        # ── Bottom: Energy Balance ──
        e_in    = [r["E_in"]    for r in self.records]
        e_store = [r["E_stored"] for r in self.records]
        e_diss  = [r["E_dissip"] for r in self.records]
        axes[2].plot(cycles, e_in,    color="gold",      linewidth=1.5, label="E_in")
        axes[2].plot(cycles, e_store, color="steelblue", linewidth=1.5, label="E_stored")
        axes[2].plot(cycles, e_diss,  color="tomato",    linewidth=1.5, label="E_dissipated")
        axes[2].set_xlabel("Cycle")
        axes[2].set_ylabel("Energy")
        axes[2].legend(fontsize=8)
        axes[2].grid(True, alpha=0.3)
        axes[2].set_xticks(cycles)

        plt.tight_layout()
        plt.savefig(save_path, dpi=150)
        print(f"\n📊 Plot Saved: {save_path}")
        plt.close()


# ─────────────────────────────────────────────
# Entry Point (Operation Verification)
# ─────────────────────────────────────────────

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(name)s | %(levelname)s | %(message)s",
    )

    print(f"=== NRA-IDE Foundation [{jst_now()}] ===\n")

    # Constraints (Default settings)
    laws = [
        BoundLaw(threshold=0.8, k=1.0, margin=0.05),
        RateLimitLaw(max_rate=0.2),
    ]

    # Node Configuration (Minimal Configuration)
    nodes = [
        DisturbanceNode("Disturbance", trigger_cycles=[5, 14], magnitude=0.5),
        DynamicsNode("Dynamics"),
        SafetyNode("SafetyCheck", laws),
    ]

    ring = NomologicalRing(nodes)
    obs  = ObservationLog()

    token = Token()   # Start from DynamicState default values

    for _ in range(20):
        token = ring.run_cycle(token)
        obs.record(token)

    print(f"Final Token: {token}")
    print(f"Energy Conserved: {token.ledger.is_conserved(tol=1e-4)}")
    obs.print_table()

    PLOT = "nra_foundation_plot.png"
    obs.plot(PLOT, threshold=0.8)
    print(f"\n=== Completed [{jst_now()}] ===")
```
